nameOverride: review
fullnameOverride: review-green

image:
  name: review-service

env:
  SPRING_APPLICATION_NAME: review
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: file:/config/application.yml,file:/config/review.yml
  LOGGING_CONFIG: file:/config/logback-spring.xml

livenessProbe_enabled: true

readinessProbe_enabled: true

configmap:
  enabled: true
  volumeMounts:
    mountPath: /config
  useLogback: true
