fullnameOverride: product-composite

image:
  name: product-composite-service

ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: http-mgm
    containerPort: 4004
    protocol: TCP

env:
  SPRING_APPLICATION_NAME: product-composite
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_CONFIG_LOCATION: file:/config/application.yml,file:/config/product-composite.yml
  LOGGING_CONFIG: file:/config/logback-spring.xml

envFromConfigRefs:
  - name: JWT_ISSUER_URI
    valueFrom:
      configMapKeyRef:
        name: configmap-cert-env
        key: JWT_ISSUER_URI

livenessProbe_enabled: true

readinessProbe_enabled: true

configmap:
  enabled: true
  volumeMounts:
    mountPath: /config
  useLogback: true

service:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 4004
      name: http-mgm
      targetPort: 4004